import { createHash, randomUUID } from "crypto";
import { CreateBucketCommand, DeleteObjectCommand, GetObjectCommand, HeadBucketCommand, HeadObjectCommand, PutBucketCorsCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { allowedExtensions, extension, mediaKind } from "./media";

export type StoredUpload={ext:string;key:string;sha256:string;kind:string;previewUrl:string|null;remove:()=>Promise<unknown>};
export const storageDriver=()=>"s3" as const;
const bucket=()=>process.env.S3_BUCKET||"astrofotografia";
let client:S3Client|undefined;
function s3(){if(!client)client=new S3Client({region:process.env.S3_REGION||"us-east-1",endpoint:process.env.S3_ENDPOINT,forcePathStyle:process.env.S3_FORCE_PATH_STYLE!=="false",credentials:process.env.S3_ACCESS_KEY&&process.env.S3_SECRET_KEY?{accessKeyId:process.env.S3_ACCESS_KEY,secretAccessKey:process.env.S3_SECRET_KEY}:undefined});return client}
function publicS3(){return new S3Client({region:process.env.S3_REGION||"us-east-1",endpoint:process.env.S3_PUBLIC_ENDPOINT||process.env.S3_ENDPOINT,forcePathStyle:process.env.S3_FORCE_PATH_STYLE!=="false",credentials:{accessKeyId:process.env.S3_ACCESS_KEY||"",secretAccessKey:process.env.S3_SECRET_KEY||""}})}
let bucketReady:Promise<void>|undefined;
function ensureBucket(){if(!bucketReady)bucketReady=(async()=>{try{await s3().send(new HeadBucketCommand({Bucket:bucket()}))}catch{await s3().send(new CreateBucketCommand({Bucket:bucket()}))}const origin=process.env.NEXT_PUBLIC_APP_URL;if(origin)await s3().send(new PutBucketCorsCommand({Bucket:bucket(),CORSConfiguration:{CORSRules:[{AllowedMethods:["PUT"],AllowedOrigins:[origin],AllowedHeaders:["*"],ExposeHeaders:["etag"],MaxAgeSeconds:3600}]}}))})().catch(e=>{bucketReady=undefined;throw e});return bucketReady}
export async function persistUpload(file:File):Promise<StoredUpload>{const ext=extension(file.name);if(!allowedExtensions.has(ext))throw new Error("UNSUPPORTED");const max=Number(process.env.MAX_UPLOAD_MB||250)*1048576;if(file.size>max)throw new Error("TOO_LARGE");const bytes=Buffer.from(await file.arrayBuffer());const sha256=createHash("sha256").update(bytes).digest("hex");const key=`originals/${new Date().getUTCFullYear()}/${randomUUID()}.${ext}`;await ensureBucket();await s3().send(new PutObjectCommand({Bucket:bucket(),Key:key,Body:bytes,ContentType:file.type||"application/octet-stream",Metadata:{sha256,"original-name":encodeURIComponent(file.name)}}));return{ext,key,sha256,kind:mediaKind(file.name),previewUrl:["jpg","jpeg","png","webp","gif"].includes(ext)?`/api/media/by-key/${encodeURIComponent(key)}`:null,remove:()=>s3().send(new DeleteObjectCommand({Bucket:bucket(),Key:key}))}}
export async function readStoredObject(key:string){const response=await s3().send(new GetObjectCommand({Bucket:bucket(),Key:key}));if(!response.Body)throw new Error("EMPTY_OBJECT");return Buffer.from(await response.Body.transformToByteArray())}
export async function createUploadUrl(input:{userId:string;name:string;type:string;size:number;sha256:string}){const ext=extension(input.name);if(!allowedExtensions.has(ext))throw new Error("UNSUPPORTED");const max=Number(process.env.MAX_UPLOAD_MB||250)*1048576;if(input.size>max)throw new Error("TOO_LARGE");await ensureBucket();const key=`originals/${input.userId}/${new Date().getUTCFullYear()}/${randomUUID()}.${ext}`;const command=new PutObjectCommand({Bucket:bucket(),Key:key,ContentType:input.type||"application/octet-stream",ContentLength:input.size,Metadata:{sha256:input.sha256,"user-id":input.userId,"original-name":encodeURIComponent(input.name)}});return{key,url:await getSignedUrl(publicS3(),command,{expiresIn:900})}}
export async function verifyUploadedObject(key:string,userId:string){if(!key.startsWith(`originals/${userId}/`))throw new Error("INVALID_KEY");const obj=await s3().send(new HeadObjectCommand({Bucket:bucket(),Key:key}));if(obj.Metadata?.["user-id"]!==userId)throw new Error("INVALID_OWNER");return{byteSize:Number(obj.ContentLength||0),sha256:obj.Metadata?.sha256||"",mimeType:obj.ContentType||"application/octet-stream"}}
